###### Class com.mode.bok.ui.R is created by jadx
###### Class com.mode.bok.ui.R.anim is created by jadx
###### Class com.mode.bok.ui.R.animator is created by jadx
###### Class com.mode.bok.ui.R.array is created by jadx
###### Class com.mode.bok.ui.R.attr is created by jadx
###### Class com.mode.bok.ui.R.bool is created by jadx
###### Class com.mode.bok.ui.R.color is created by jadx
###### Class com.mode.bok.ui.R.dimen is created by jadx
###### Class com.mode.bok.ui.R.drawable is created by jadx
###### Class com.mode.bok.ui.R.id is created by jadx
###### Class com.mode.bok.ui.R.integer is created by jadx
###### Class com.mode.bok.ui.R.interpolator is created by jadx
###### Class com.mode.bok.ui.R.layout is created by jadx
###### Class com.mode.bok.ui.R.menu is created by jadx
###### Class com.mode.bok.ui.R.mipmap is created by jadx
###### Class com.mode.bok.ui.R.navigation is created by jadx
###### Class com.mode.bok.ui.R.plurals is created by jadx
###### Class com.mode.bok.ui.R.raw is created by jadx
###### Class com.mode.bok.ui.R.string is created by jadx
###### Class com.mode.bok.ui.R.style is created by jadx
###### Class com.mode.bok.ui.R.xml is created by jadx